name: Convert README to HTML

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Usa la versione Python più recente disponibile

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 markdown

      - name: Generate HTML from README
        run: |
          python generate_html.py

      - name: Create new branch for HTML update
        id: create_branch
        run: |
          # Crea un timestamp per il nome della branch
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          BRANCH_NAME="update-html-${TIMESTAMP}"
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH_NAME"
          git add docs/index.html
          git commit -m "Update generated HTML from README.md"
          git push -u origin "$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main  # sostituisci con il branch protetto, se è diverso da `main`
          source_branch: ${{ env.branch_name }}
          pr_title: "Automatic HTML Update from README.md"
          pr_body: "This pull request updates the automatically generated HTML page from the README.md file."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
