name: Restrict Modifications to Categories Section

on:
  pull_request:
    paths:
      - "README.md"

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clona l'intera cronologia per il confronto

      - name: Get diff of README.md
        id: get_diff
        run: |
          # Delimitatori della sezione
          START="<!-- START CATEGORIES -->"
          END="<!-- END CATEGORIES -->"
          
          # Estrai le modifiche rispetto al commit precedente
          DIFF=$(git diff HEAD^ -- README.md)
          
          # Debug: Mostra la differenza calcolata
          echo "DIFF CONTENT:"
          echo "$DIFF"
          
          # Usa awk per verificare se ci sono modifiche al di fuori della sezione consentita
          IN_SECTION=false
          OUTSIDE_CHANGES=false
          
          echo "$DIFF" | while IFS= read -r line; do
            # Se troviamo il delimitatore di inizio, entriamo nella sezione
            if echo "$line" | grep -q "$START"; then
              IN_SECTION=true
              continue
            fi
            
            # Se troviamo il delimitatore di fine, usciamo dalla sezione
            if echo "$line" | grep -q "$END"; then
              IN_SECTION=false
              continue
            fi
            
            # Se troviamo modifiche fuori dalla sezione, impostiamo OUTSIDE_CHANGES
            if [[ "$line" =~ ^(\+|\-) ]] && [ "$IN_SECTION" = false ]; then
              OUTSIDE_CHANGES=true
              break
            fi
          done
          
          # Imposta lo stato in base al risultato del controllo
          if [ "$OUTSIDE_CHANGES" = true ]; then
            echo "status=failure" >> $GITHUB_ENV
            echo "The changes are outside the allowed 'Categories' section." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "status=success" >> $GITHUB_ENV
            echo "The changes are within the allowed 'Categories' section." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Comment on pull request if changes are outside allowed section
        uses: actions/github-script@v7
        if: failure()  # Esegui solo se il controllo fallisce
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "❌ Changes to the README.md have been detected outside the 'Categories' section. Please read the CONTRIBUTING.md file."
            });
