name: Restrict Modifications to Categories Section

on:
  pull_request:
    paths:
      - "README.md"

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clona l'intera cronologia per il confronto

      - name: Get diff of README.md
        id: get_diff
        run: |
          # Delimitatori della sezione
          START="<!-- START CATEGORIES -->"
          END="<!-- END CATEGORIES -->"
          
          # Estrai le modifiche rispetto al commit precedente
          DIFF=$(git diff "HEAD^" -- README.md)
          
          # Debug: Mostra la differenza calcolata
          echo "DIFF CONTENT:"
          echo "$DIFF"
          
          # Verifica se le modifiche sono esclusivamente all'interno della sezione consentita
          IN_SECTION=false
          OUTSIDE_CHANGES=false
          
          while IFS= read -r line; do
            # Controlla l'inizio della sezione consentita
            if echo "$line" | grep -q "$START"; then
              IN_SECTION=true
              continue
            fi
            
            # Controlla la fine della sezione consentita
            if echo "$line" | grep -q "$END"; then
              IN_SECTION=false
              continue
            fi
            
            # Verifica se ci sono modifiche al di fuori della sezione
            if [[ "$line" =~ ^(\+\+|\-\-) ]]; then
              continue
            elif [[ "$line" =~ ^(\+|\-) ]] && [ "$IN_SECTION" = false ]; then
              OUTSIDE_CHANGES=true
              break
            fi
          done <<< "$DIFF"
          
          # Imposta lo stato in base al risultato del controllo
          if [ "$OUTSIDE_CHANGES" = true ]; then
            echo "status=failure" >> $GITHUB_ENV
            echo "The changes are outside the allowed 'Categories' section." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "status=success" >> $GITHUB_ENV
            echo "The changes are within the allowed 'Categories' section." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Comment on pull request
        uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = process.env.status;
            if (status === 'success') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "✅ Changes to the README.md file are limited to the 'Categories' section, great!"
              });
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "❌ Changes to the README.md have been detected outside the 'Categories' section. Please read the CONTRIBUTING.md file."
              });
            }
